# -*- coding: utf-8 -*-
"""III_II

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1It_Gq1ft1xJxBvqA1cOevk6GpJRqrM9L
"""

import 라이브러리명
from 라이브러리명 import 명령어

browser.get(url)

browser.page_source

soup = BeautifulSoup(데이터, 'htmi.parser')
soup = BeautifulSoup(browser.page_source, 'htmi.parser')

soup.select('태그정보')
soup.select('태그명')
soup.select('class 속성값')
soup.select('#id속성값')
soup.select('부모태그정보>지식태그정보')

tag_list = soup.select()



<태그> <태그>
<태그명> </태그명>
<태그ㅁ